server:
  port: "8080"
  readTimeout: 10s
  writeTimeout: 10s

mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/nft_auction?charset=utf8mb4&parseTime=True&loc=Local"
  maxOpenConns: 100
  maxIdleConns: 20
  connMaxLifetime: 30m

blockchain:
  rpcEndpoint: "https://ethereum-sepolia-rpc.publicnode.com" # 测试网RPC
  WSRpcEndpoint: "wss://ethereum-sepolia-rpc.publicnode.com"
  ContractAddr: "0x0E5Cd5E3fe2541E2563090FC99f0Ba282353dC2A" # NFT合约地址
  ERC721ContractAddr: "0x8174da3510e4C0373db82b92AB7949AfF75e7C25"
  privateKey: "" # 加密存储
  StartBlock: 1000000
  PollInterval: 20
  
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  poolSize: 20